[build]
  # Clean Node.js build process
  command = "npm ci && npm run build"
  
  # Directory to publish (build output)
  publish = "dist"
  
[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Production environment
  NODE_ENV = "production"
  # Production API URL - points to Heroku backend
  VITE_API_URL = "https://law-agent-ai-prod-91772216e445.herokuapp.com"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
