services:
  - type: web
    name: legal-rag-chatbot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.13
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION
        value: law_chunks
    healthCheckPath: /health

  - type: web
    name: legal-rag-chatbot-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: ./
    envVars:
      - key: VITE_API_URL
        value: https://law-ai-agent.onrender.com
