name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build, Push and Deploy to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        # The email address associated with your Heroku account
        email: ${{ secrets.HEROKU_EMAIL }}
        # Heroku API key associated with provided user's email
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        # Name of the heroku app to deploy to
        heroku_app_name: law-agent-ai-prod
        # (Optional, default: "./")
        # Dockerfile directory.
        dockerfile_directory: ./
        # (Optional, default: "Dockerfile")
        # Dockerfile name.
        dockerfile_name: Dockerfile
        # (Optional, default: "")
        # Additional options of docker build command.
        docker_options: "--no-cache"
        # (Optional, default: "web")
        # Select the process type for which you want the docker container to be used.
        process_type: web

  set-env-vars:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Set Heroku Config Vars
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: law-agent-ai-prod
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        justlogin: true
        
    - name: Set environment variables
      run: |
        heroku config:set \
          DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          SECRET_KEY="${{ secrets.SECRET_KEY }}" \
          GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" \
          QDRANT_URL="${{ secrets.QDRANT_URL }}" \
          QDRANT_API_KEY="${{ secrets.QDRANT_API_KEY }}" \
          STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
          STRIPE_PUBLISHABLE_KEY="${{ secrets.STRIPE_PUBLISHABLE_KEY }}" \
          STRIPE_WEBHOOK_SECRET="${{ secrets.STRIPE_WEBHOOK_SECRET }}" \
          GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
          GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
          -a law-agent-ai-prod
